name: Build CCTVDownloader

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.8.0'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2022_64'
        
    - name: Manual Setup vcpkg
      shell: cmd
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg
        git checkout fd5e5828469e011406859b56f2d5e54c0e64c126
        call bootstrap-vcpkg.bat
        
    - name: Install Dependencies
      shell: cmd
      run: |
        .\vcpkg\vcpkg.exe install cpr curl openssl:x64-windows --triplet x64-windows
        
    - name: Setup MSVC environment
      uses: ilammy/msvc-dev-cmd@v1
      
    - name: Build
      shell: cmd
      env:
        QT_PATH: ${{ env.Qt6_DIR }}
        VCPKG_PATH: ${{ github.workspace }}\vcpkg\installed\x64-windows
      run: |
        qmake CCTVVideoDownloader.pro "CONFIG+=release"
        nmake
        
    - name: Deploy Qt Dependencies
      shell: cmd
      env:
        QT_PATH: ${{ env.Qt6_DIR }}
      run: |
        set PATH=%QT_PATH%\bin;%PATH%
        windeployqt release\CCTVVideoDownloader.exe --dir release\
        
    - name: Copy Extra DLLs
      shell: cmd
      run: |
        copy vcpkg\installed\x64-windows\bin\libcurl.dll release\
        copy vcpkg\installed\x64-windows\bin\cpr.dll release\
        copy vcpkg\installed\x64-windows\bin\libcrypto-3-x64.dll release\
        copy vcpkg\installed\x64-windows\bin\libssl-3-x64.dll release\
        copy vcpkg\installed\x64-windows\bin\zlib1.dll release\
        xcopy /Y /E src\decrypt release\decrypt\

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: CCTVVideoDownloader-Release
        path: release/
